title: "Nickolas Arustamyan"
author: Nickolas Arustamyan
email: nickarust@gmail.com
description: >- # your description
  Ph.D. student in Mathematics with a focus on Scientific Computing and Machine Learning.
remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

markdown: kramdown
baseurl: "" 
url: "https://nickarust.github.io"